-- AlterTable
ALTER TABLE "Order" ADD COLUMN "pointDiscountAmount" DECIMAL(12,2) NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "pointsReserved" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "pointsConsumed" INTEGER NOT NULL DEFAULT 0;
