-- AlterTable
ALTER TABLE "ReferralProgramConfig" ADD COLUMN     "bronzePoints" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "bronzeThreshold" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "diamondPoints" INTEGER NOT NULL DEFAULT 3000,
ADD COLUMN     "diamondThreshold" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "goldPoints" INTEGER NOT NULL DEFAULT 1000,
ADD COLUMN     "goldThreshold" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "silverPoints" INTEGER NOT NULL DEFAULT 250,
ADD COLUMN     "silverThreshold" INTEGER NOT NULL DEFAULT 10;
