-- AlterTable
ALTER TABLE "PointTransaction" ALTER COLUMN "amount" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "remainingAmount" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "pointBalance" SET DEFAULT 0,
ALTER COLUMN "pointBalance" SET DATA TYPE DOUBLE PRECISION;
