/** Tên biến môi trường — OTP & bcrypt */
export const OTP_ENV = {
  EXPIRES_MINUTES: 'OTP_EXPIRES_MINUTES',
  RATE_LIMIT_WINDOW_MINUTES: 'OTP_RATE_LIMIT_WINDOW_MINUTES',
  RATE_LIMIT_MAX: 'OTP_RATE_LIMIT_MAX',
  BCRYPT_SALT_ROUNDS: 'BCRYPT_SALT_ROUNDS',
} as const;

export const OTP_DEFAULTS = {
  EXPIRES_MINUTES: 2,
  RATE_LIMIT_WINDOW_MINUTES: 10,
  RATE_LIMIT_MAX: 3,
  BCRYPT_SALT_ROUNDS: 8,
} as const;
